[theme]
primaryColor = "#087e72"
backgroundColor = "#f7faf9"
secondaryBackgroundColor = "#e9f5f2"
textColor = "#17343a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
