[theme]
primaryColor = "#234b44"
backgroundColor = "#f8faf8"
secondaryBackgroundColor = "#f0f4f1"
textColor = "#192d2b"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
